# Generated by Django 5.1.5 on 2025-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default='Guest', help_text='Enter user name', max_length=50)),
                ('emd_email', models.EmailField(max_length=254, unique=True)),
                ('emp_dob', models.DateField()),
                ('emp_creation_Date_Time', models.DateTimeField(auto_now_add=True)),
                ('emp_last_login', models.DateTimeField(auto_now=True)),
                ('emp_contact', models.IntegerField()),
                ('emp_city', models.CharField(choices=[('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Jbp', 'Jbp'), ('Rewa', 'Rewa')], max_length=50, verbose_name='city')),
                ('emp_description', models.TextField()),
                ('emp_status', models.BooleanField()),
                ('emp_work_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Qualification',
            field=models.CharField(choices=[('b-tech', 'b-tech'), ('m-tech', 'm-tech'), ('b-sc', 'b-sc')], db_index=True, max_length=100, null=True, verbose_name='Quali'),
        ),
    ]
